# Generated by Django 4.2.4 on 2023-08-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsible_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_milestone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasklist.project'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Service',
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In progress'), (2, 'Internal Review'), (3, 'Awaiting Approval'), (4, 'Paused'), (5, 'Canceled'), (6, 'Complete')], default=0, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('priority', models.IntegerField(choices=[(0, 'Normal'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=0, verbose_name='Priority')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task', related_query_name='creator_of', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasklist.project')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='service', to='tasklist.service', verbose_name='Service')),
                ('responsible_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', related_query_name='reponsible_to', to=settings.AUTH_USER_MODEL, verbose_name='Responsible To')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='milestone_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasklist.milestone'),
            preserve_default=False,
        ),
    ]
