# Generated by Django 4.2.4 on 2023-08-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasklist', '0002_remove_task_created_by_remove_task_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='milestone_ptr',
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='parent_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasklist.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=0, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='service', to='tasklist.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In progress'), (2, 'Internal Review'), (3, 'Awaiting Approval'), (4, 'Paused'), (5, 'Canceled'), (6, 'Complete')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=None, max_length=150, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milestone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', related_query_name='creator_of', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='parent_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', related_query_name='from_project', to='tasklist.project', verbose_name='Parent Project'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='responsible_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_milestones', related_query_name='reponsible_to', to=settings.AUTH_USER_MODEL, verbose_name='Responsible To'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasklist.milestone'),
        ),
    ]
