# Generated by Django 4.2.4 on 2023-08-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0004_task_created_by_task_responsible_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Is template'),
        ),
    ]
