# Generated by Django 4.2.4 on 2023-08-06 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0005_milestone_is_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_project',
        ),
        migrations.AlterField(
            model_name='milestone',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', related_query_name='from_project', to='tasklist.project', verbose_name='Parent Project'),
        ),
    ]
