# Generated by Django 4.2.4 on 2023-08-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0006_remove_task_parent_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='checkin_requirement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='insignia_requirement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='portal_requirement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sentinel_requirement',
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='tasklist.service'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', related_query_name='milestones_from_project', to='tasklist.project', verbose_name='Parent Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='tasks_from_project', to='tasklist.milestone', verbose_name='Task'),
        ),
    ]
