# Generated by Django 4.2.4 on 2023-08-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0009_alter_task_parent_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_milestone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='tasks_from_milestone', to='tasklist.milestone', verbose_name='Parent milestone'),
            preserve_default=False,
        ),
    ]
