# Generated by Django 4.2.4 on 2023-09-21 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Manufacturer')),
                ('model_code', models.CharField(max_length=10, verbose_name='Model Code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/models', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number')),
                ('ICCID', models.CharField(blank=True, max_length=20, null=True, verbose_name='Integrated Circuit Card Identifier')),
                ('IMEI', models.CharField(blank=True, max_length=15, null=True, verbose_name='International Mobile Equipment Identity')),
                ('knox_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Knox ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.model')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
