# Generated by Django 4.2.4 on 2023-09-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='AssetModel',
        ),
    ]
