# Generated by Django 4.2.4 on 2023-09-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_model_assetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_line_1',
            field=models.CharField(default=1, max_length=35, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_2',
            field=models.CharField(default=1, max_length=35, verbose_name='Address Line 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=1, max_length=85, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default=1, max_length=85, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(default=1, max_length=20, verbose_name='Zipcode'),
            preserve_default=False,
        ),
    ]
