# Generated by Django 4.2.4 on 2023-09-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='ICCID',
            new_name='iccid',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='IMEI',
            new_name='imei',
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='asset',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.shipment'),
        ),
    ]
