# Generated by Django 4.2.4 on 2023-09-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_shipment_rename_iccid_asset_iccid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_in', to='assets.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_out', to='assets.location'),
            preserve_default=False,
        ),
    ]
