# Generated by Django 4.2.4 on 2023-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_shipment_destination_shipment_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(default='', max_length=85, verbose_name='Carrier'),
            preserve_default=False,
        ),
    ]
