# Generated by Django 4.2.4 on 2023-09-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_shipment_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Address Line 2'),
        ),
    ]
