# Generated by Django 4.2.4 on 2023-09-23 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_location_address_line_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='parent',
        ),
        migrations.AddField(
            model_name='asset',
            name='current_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_assets', to='assets.shipment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='assets',
            field=models.ManyToManyField(related_name='shipments_included_in', to='assets.asset'),
        ),
    ]
