# Generated by Django 4.2.4 on 2023-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_shipment_remove_assetmodel_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Scheduled'), (1, 'In transit'), (2, 'Delivered'), (3, 'Canceled')], default=0, verbose_name='Status'),
        ),
    ]
