# Generated by Django 4.2.4 on 2023-09-24 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_shipment_arrival_date_shipment_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Ba-b0-9]*$', 'Enter an alphanumeric value')], verbose_name='Code'),
        ),
    ]
