# Generated by Django 4.2.4 on 2023-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='iccid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ICCID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IMEI'),
        ),
    ]
