# Generated by Django 4.2.4 on 2023-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
    ]
