# Generated by Django 4.2.4 on 2023-09-24 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_shipment_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]*$', 'Enter an alphanumeric value')], verbose_name='Code'),
        ),
    ]
