# Generated by Django 4.2.4 on 2023-09-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_asset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_container',
            field=models.BooleanField(default=False, verbose_name='Is a Container'),
        ),
    ]
