# Generated by Django 4.2.4 on 2023-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_asset_is_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='assets',
        ),
        migrations.AddField(
            model_name='shipment',
            name='assets',
            field=models.BinaryField(blank=True, null=True, verbose_name='Assets'),
        ),
    ]
