# Generated by Django 4.2.4 on 2023-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_remove_shipment_assets_shipment_assets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['arrival_date']},
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['departure_date', 'arrival_date'], name='assets_ship_departu_a97ac7_idx'),
        ),
    ]
