# Generated by Django 4.2.4 on 2023-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='assets',
            field=models.JSONField(blank=True, null=True, verbose_name='Assets'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Packed'), (2, 'Delivered'), (3, 'Canceled')], default=0, verbose_name='Status'),
        ),
    ]
