# Generated by Django 4.2.4 on 2023-10-01 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_alter_shipment_assets_alter_shipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='assets',
            new_name='locked_assets',
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.shipment'),
        ),
    ]
