# Generated by Django 4.2.4 on 2023-10-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_options'),
        ('assets', '0020_rename_assets_shipment_locked_assets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['status', 'arrival_date']},
        ),
        migrations.AddField(
            model_name='shipment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code', 'model'], name='assets_asse_code_a701f3_idx'),
        ),
    ]
