# Generated by Django 4.2.4 on 2023-10-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['travel_in_date']},
        ),
    ]
