# Generated by Django 4.2.4 on 2023-08-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at Date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('travel_in_date', models.DateField(verbose_name='Travel In Date')),
                ('travel_out_date', models.DateField(verbose_name='Travel Out Date')),
                ('timetracking_url', models.URLField(blank=True, null=True, verbose_name='Timetracking URL')),
                ('external_project_url', models.URLField(blank=True, null=True, verbose_name='External Project URL')),
                ('sharepoint_url', models.URLField(blank=True, null=True, verbose_name='Sharepoint URL')),
            ],
        ),
    ]
